version: "3.4"
services:
####################################### DB Server ######################################
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CTP3.2-ubuntu"
    volumes:
      - sqldata2:/var/opt/mssql 
    ports:
      - 52669:1433
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Standard"
    restart: always                   
volumes:
  sqldata2:
